# Generated by Django 4.0.3 on 2022-04-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Agenda',
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.TextField(default='abuja'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetup',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
